### ISSUE TITLE
アカウント作成画面を作成する

### ISSUE THREAD

**Issue by ryohakjae114** [ryohakjae114/miniblog#20]
* sign_up、sign_in、passwords/new、passwords/edit、users/editのviewファイルをインストールする
  `rails g devise:views`
  * installされた不要なdeviseのviewファイルを削除
* hamlに変換する
  `rails haml:erb2haml`
* sessions/new.html.hamlをカスタマイズする
* 日本語化する
  * userのカラム
  * nameのエラーを'英文字のみが使えます。スペースは使用できません。'に変更
* config/localesにmodels.ja.ymlを作成 
```yml
ja:
  activerecord:
    models:
      user: 'ユーザー'
    attributes:
      user:
        name: '名前'
        ~
　validates:
      user:
        name:
          format: '英文字のみが使えます。スペースは使用できません。'
```
  * user.rbのnameのformatのバリエーションエラーメッセージをtメソッドに書き換える
  * ページタイトル
    * config/localesにviews.ja.ymlを作成
    ```yml
    ja:
     devise:
      registrations:
        new:
          title: 'アカウント作成'
    ```
    * タイトルをtメソッドに書き換える
* nameとpasswordのヒントを表示する
```ruby
simple_form:
  hints:
    user:
      name: "サインインに使用するユーザ名を英文字のみで作成してください。スペースは使用できません。"
      password: "パスワードを10桁以上で作成してください"
```
* ユーザ作成後のメッセージを日本語にする
  * ja.devise.registrations.user.signed_upをviews.ja.ymlで指定する
